### ISSUE TITLE
run buit-it failed

### ISSUE THREAD

**Issue by zhiyongww** [pemsley/coot#24]
```
/usr/bin/ld: ungz.o: in function `ungz_':
/home/ywen232625/autobuild/building/ywen232625-manjaro_2019-08-07__T14_30_24/Raster3D_3.0-3/ungz.c:20: 警告：the use of `tempnam' is dangerous, better use `mkstemp'
URL transformed to HTTPS due to an HSTS policy
--2019-08-07 22:37:54--  https://www2.mrc-lmb.cam.ac.uk/personal/pemsley/coot/source/pre-releases/right.tar.gz
已载入 CA 证书“/etc/ssl/certs/ca-certificates.crt”
正在解析主机 www2.mrc-lmb.cam.ac.uk (www2.mrc-lmb.cam.ac.uk)... 131.111.85.100
正在连接 www2.mrc-lmb.cam.ac.uk (www2.mrc-lmb.cam.ac.uk)|131.111.85.100|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 404 Not Found
2019-08-07 22:37:55 错误 404：Not Found。
```

I am trying to build coot in Manjaro, and I got this error.
It seems that this file does not exist.

**Comment by cdputnam** [comment]
It appears that the part of the build-it script that identifies the latest pre-version from the https://www2.mrc-lmb.cam.ac.uk/Personal/pemsley/coot/source/pre-releases/index.html file is not working. It's getting "right.tar" from a "right" in a HTML tag rather than the file name. I'm guessing that there was a change in how the index.html file is generated by the server.

The following patch to the build-it script gets me past this error.

[build-it-diff.txt](https://github.com/pemsley/coot/files/3494588/build-it-diff.txt)

**Comment by pemsley** [comment]
Thanks, Fixed now.
