### ISSUE TITLE
`set_scroll_wheel_map()` does not update scroll wheel map indicator in display manager (0.9.8.91)

### ISSUE THREAD

**Issue by olibclarke** [pemsley/coot#81]
Hi Paul,

The scripting function `set_scroll_wheel_map(map_id)` and `set_scrollable_map(map_id)` both set the scroll_wheel_map correctly (as judged by which contour level changes), but the visual indicator of which map is scrollable in the display manager does not update (and is therefore incorrect). Tested in 0.9.8.91 (CCP4).

Cheers
Oli

**Comment by olibclarke** [comment]
Ok thanks Paul - is `main` ready for production use then? Or still hold off a bit

**Comment by pemsley** [comment]
Yes it is ready, I'd say. We are tidying up with thing like progress bars, but now that the new ligand tool is in, it's basically done.

**Comment by olibclarke** [comment]
Woohoo! time to fire up homebrew again

**Comment by pemsley** [comment]
Fixed in c6e18bbb716a8a42f66d4bd464a7f5438386b495 in `main` branch.

**Comment by olibclarke** [comment]
Thanks Paul - this one is minor so not worth it I guess, but will other fixes still be provided for the `refinement` branch until `main` is completely stable? My perception is that `1.x` is great and heading towards usability but it still may be a little while before I would want to use it for building full time (at least on a Mac).

**Comment by pemsley** [comment]
@olibclarke my plan is for GUI work to be in Coot 1.1 (GTK4/main) only. I no longer want to work with GTK2.

Problems like link detection and detection of cis peptides is something that is independent of the graphics, so that can happen in the `refinement` branch and be merged into `main`.  Last year I said that I'd maintain the `refinement` branch for ~18 months after the release of Coot 1. By not changing the gui of `refinement` it makes handling the merging tolerable, so I can continue to do that for another year - until Christmas 2024, say. The `refinement` branch may move to 0.9.9 at some stage.
